---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: "gfgdeployment"
spec: 
  replicas: 3
  selector:
    matchLabels:
      dc: "In"
  template:
    metadata:
      name: "mypod"
      labels:
        dc: "In"
    spec:
      containers:
      - name: "backend"
        image: ashishdev213/wellness-backend
        imagePullPolicy: Always
        ports:
        - containerPort: 8000 
      - name: "frontend"
        image: ashishdev213/wellness-frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 3000 

---

apiVersion: v1
kind: Service
metadata:
  name: "MindScopeService"
spec:
  selector:
    dc: "In"
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31933
  type: LoadBalancer
